Exercise3app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('accounts/register', views.registration, name='registration'),
    path('idol/profile/<pk>', views.idoldetailview,  name='idoldetailview'),
    path('idol/', views.idolfulllist, name='idolfulllist'),
    path('idol/register', views.idolregister, name='idolregister'),
    path('idol/profile/<pk>/edit', views.idol_edit, name='idol_edit')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('Exercise3app.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='welcome'), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Exercise3app/models.py
from django.core.validators import MaxValueValidator
from django.db import models


class IdolDetail(models.Model):
	aboutme = models.TextField()
	birthday = models.DateField()
	city = models.CharField(max_length=20)
	height = models.PositiveIntegerField(validators=[MaxValueValidator(300)], help_text='Please input in CM')
	profilepicture = models.ImageField(upload_to='gallery', default='gallery/default.png', null=True, blank=True)
	namefirst = models.CharField(max_length=100)
	namelast = models.CharField(max_length=100)
	namemiddle = models.CharField(max_length=100, null=True, blank=True)
	nickname = models.CharField(max_length=15)
	province = models.CharField(max_length=20)
	school = models.CharField(max_length=50)
	votes = models.PositiveIntegerField(default=0, null=True, blank=True)

	def __str__(self):
		return self.namefirst + " " + self.namelast
	

class SongData(models.Model):
	title = models.CharField(max_length=100)

	def __str__(self):
		return self.title


class IdolSongsPosition(models.Model):
	idolsinger = models.ForeignKey(IdolDetail, on_delete=models.SET_NULL, null=True)
	position = models.CharField(max_length=50, null=True, blank=True)
	songtitle = models.ForeignKey(SongData, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.idolsinger.nickname + " - " + self.songtitle.title + " (" + (self.position or "") + ")"

Exercise3app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import IdolDetail

class RegistrationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class IdolCreationForm(forms.ModelForm):
	class Meta:
		model = IdolDetail
		exclude = ('', )

Exercise3app/views.py
import operator

from .forms import RegistrationForm, IdolCreationForm
from .models import IdolDetail
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render,  redirect, get_object_or_404



@login_required
def idoldetailview(request, pk):
	idolinfo = get_object_or_404(IdolDetail, pk=pk)
	return render(request, 'Exercise3app/idoldetailview.html', {'idolinfo' : idolinfo})


@login_required
def idolfulllist(request):
	if 'search_function' in request.GET:
		search_idol_term = request.GET.get('search_function').split(" ")
		idolwholelist = IdolDetail.objects.all()
		for term in search_idol_term:
			idolwholelist = idolwholelist.filter(
				Q(namefirst__icontains=term) | 
				Q(namelast__icontains=term) | 
				Q(namemiddle__icontains=term) | 
				Q(nickname__icontains=term))
		idolwholelist = idolwholelist.distinct()
	else:
		idolwholelist = IdolDetail.objects.order_by('namelast')
	return render(request, 'Exercise3app/idolfulllist.html', {'idolwholelist' : idolwholelist})


@login_required
def idolregister(request):
	if request.method == 'POST':
		forms = IdolCreationForm(request.POST, request.FILES)
		if forms.is_valid():
			forms.save()
			formskey = forms.save(commit=False)
			return redirect('idoldetailview', pk=formskey.pk)
	else:
		forms = IdolCreationForm()
	return render(request, 'Exercise3app/idolregister.html', {'forms' : forms})


@login_required
def idol_edit(request, pk):
	formsinfo = get_object_or_404(IdolDetail, pk=pk)
	if request.method == 'POST':
		forms = IdolCreationForm(request.POST, request.FILES, instance=formsinfo)
		if forms.is_valid():
			forms.save()
			formskey = forms.save(commit=False)
			return redirect('idoldetailview', pk=formskey.pk)
	else:
		forms = IdolCreationForm(instance = formsinfo)
	return render(request, 'Exercise3app/idolregister.html', {'forms' : forms})


def registration(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('login.html')
	else:
		form = RegistrationForm()
	return render(request, 'registration/registration.html', {'form' : form})


def welcome(request):
	idoltoplist = IdolDetail.objects.order_by('-votes')[0:4]
	return render(request, 'Exercise3app/welcome.html', {'idoltoplist' : idoltoplist})

Exercise3app/templates/Exercise3app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'Exercise3/style.css' %}">
	<title>JapanSmile</title>
</head>
<body>
	<header style="padding: 12px;">
		<div>
			<h1 class="text-center headerlink" style="font-family:'Advent Pro'">JapanSmile</h1>
		</div>
		<div class="text-right loginbuttonposition">
			{% if user.is_authenticated %}
			<p>Logged in as: {{ user.username }}<small>(<a href="{% url 'logout' %}">logout?</a>)</small></p>
			{% else %}
			<a href="{% url 'login' %}">Log In</a>
			{% endif %}
		</div>
	</header>
	<div class="container body-padding">
	    {% block content %}
	    {% endblock %}
    </div>
    <footer class="fixed-bottom">
    	<div class="text-center">
    		<p>THIS IS FOR TESTING / EDUCATIONAL PURPOSES ONLY. ALL RIGHTS RESERVED TO RESPECTED OWNERS.</p>
    	</div>
    </footer>
</body>
</html>

Exercise3app/templates/Exercise3app/idoldetailview.html
{% extends 'Exercise3app/base.html'%}

{% block content %}
<div class="text-center" style="padding-left: 20%; padding-right: 20%;">
	{% if idolinfo.profilepicture %}
		<img style="height: 360px; width: 260px" src="{{ idolinfo.profilepicture.url }}">
	{% else %}
		<p>NO IMAGE</p>
	{% endif %}
	<h2 style="font-family: fantasy;">{{idolinfo.nickname }}</h2>
	<p>&nbsp&nbsp&nbsp<i>"{{ idolinfo.aboutme }}"</i></p>
</div>
<p style="font-size: 20px;"><i>Information</i></p>
<hr>	
<table>
	<tr>
		<td>First name: </td>
		<td><strong>{{idolinfo.namefirst}}</strong></td>
	</tr>
	<tr>
		<td>Last name: </td> 
		<td><strong>{{idolinfo.namelast}}</strong></td>
	</tr>
	<tr>
		<td>Middle name: </td>
		<td><strong>{{idolinfo.namemiddle | default_if_none:"N/A"}}</strong></td>
	</tr>
	<tr>
		<td>Birthday: </td>
		<td><strong>{{idolinfo.birthday}}</strong></td>
	</tr>
	<tr>
		<td>Height: </td>
		<td><strong>{{idolinfo.height}}CM</strong></td>
	</tr>
	<tr>
		<td>School: </td>
		<td><strong>{{idolinfo.school}}</strong></td>
	</tr>
	<tr>
		<td>City: </td>
		<td><strong>{{idolinfo.city}}</strong></td>
	</tr>
	<tr>
		<td>Province: </td> 
		<td><strong>{{idolinfo.province}}</strong></td>
	</tr>
</table>
<br>
<br>
<p style="font-size: 20px;"><i>Singles Participation</i></p>
<hr>
<div>
	<table>
		{% if idolinfo.idolsongsposition_set.all %}
			{% for songs in idolinfo.idolsongsposition_set.all %}
				<tr>
					<td>
						{{songs.songtitle}} 
						{% if songs.position %}
							({{songs.position}})
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		{% else %}
			<p>wawang bata walang kanta</p>			
		{% endif %}
	</table>
</div>
<br>
<div class="footer">
	<a class="btn btn-dark" href="{% url 'welcome' %}" >Go Back to Top 4 List</a>
	<a class="btn btn-dark" href="{% url 'idol_edit' pk=idolinfo.pk %}">Edit Idol info</a>
</div>
{% endblock %}

Exercise3app/templates/Exercise3app/idolfulllist.html
{% extends 'Exercise3app/base.html'%}

{% block content %}
<div class="row">
	<div class="col-sm-12">
	<form method="GET" action=".">
		<input type=text name="search_function" style="width: 92%">
		<button class="btn btn-dark">Search</button>
	</form>
	</div>
</div>
<hr>
<div class="row">
	<table>
		{% for idols in idolwholelist %}
			<tr>
				<td style="padding-top: 5px">
					<a href="{% url 'idoldetailview' pk=idols.pk %}">{{idols.namefirst}} ({{idols.nickname}}) {{idols.namemiddle | default_if_none:""}} {{ idols.namelast}}</a>
				</td>
			</tr>
		{% endfor  %}
	</table>
</div>

<div style="position: absolute; bottom: 50px;">
	<a class="btn btn-dark" href="{% url 'welcome' %}">Go Back to Top 4 List</a>
	<a class="btn btn-dark" href="{% url 'idolregister' %}">Click here to register new Idol</a>
</div>
{% endblock %}

Exercise3app/templates/Exercise3app/idolregister.html
{% extends 'Exercise3app/base.html'%}

{% block content %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
		<table>
			<tr>
				<td>First Name: </td>
				<td>{{forms.namefirst}}</td>
				<td>{{forms.namefirst.errors}}</td>
			</tr>
			<tr>
				<td>Last Name: </td>
				<td>{{forms.namelast}}</td>
				<td>{{forms.namelast.errors}}</td>
			</tr>
			<tr>
				<td>Middle Name: </td>
				<td>{{forms.namemiddle}}</td>
				<td>{{forms.namemiddle.errors}}</td>
			</tr>
			<tr>
				<td>Nick Name: </td>
				<td>{{forms.nickname}}</td>
				<td>{{forms.nickname.errors}}</td>
			</tr>
			<tr>
				<td>Birthday: </td>
				<td>{{forms.birthday}}</td>
				<td>{{forms.birthday.errors}}</td>
			</tr>
			<tr>
				<td>Height: </td>
				<td>{{forms.height}}<small>Please enter in CM</small></td>
				<td>{{forms.height.errors}}</td>
			</tr>
		</table>
		<hr>
		<table>		
			<tr>
				<td>School: </td>
				<td>{{forms.school}}</td>
				<td>{{forms.school.errors}}</td>
			</tr>
			<tr>
				<td>City: </td>
				<td>{{forms.city}}</td>
				<td>{{forms.city.errors}}</td>
			</tr>
			<tr>
				<td>Province: </td>
				<td>{{forms.province}}</td>
				<td>{{forms.province.errors}}</td>
			</tr>
			<tr>
				<td>About Me: </td>
				<td>{{forms.aboutme}}</td>
				<td>{{forms.aboutme.errors}}</td>
			</tr>
			<tr>
				<td>Profile Picture: </td>
				<td>{{forms.profilepicture}}</td>
				<td>{{forms.profilepicture.errors}}</td>
			</tr>
		</table>
	<br>
	<div class="row">
		<div class="col-sm-4">
			<a class="btn btn-dark" href="{% url 'welcome' %}">Go back</a>
			<button class="btn btn-dark" type="submit">Submit</button>
		</div>
	</div>
</form>

{% endblock %}

Exercise3app/templates/Exercise3app/welcome.html
{% extends 'Exercise3app/base.html'%}

{% block content %}
	<div class="row">
		{% if user.is_authenticated %}
			<h4>Welcome my friend {{ user.username }}!</h4>
		{% else %}
			<h4> Welcome annonymous user! Please login to view idol details</h4>
		{% endif %}
	</div>
	<div class="row">
		<div class="col-sm-12">
			<p><center><strong>Here is the top 4 from the Election!</strong></center></p>
		</div>
	</div>
	<div class="row">
		{% for idollist in idoltoplist %}
			<div class="col-sm-3">
				<a href="{% url 'idoldetailview' pk=idollist.pk %}">
					{% if idollist.profilepicture %}
						<img style="height: 360px; width: 260px" src="{{idollist.profilepicture.url}}">
					{% else %}
						{{idollist.nickname}}
					{% endif %}
				</a>
			</div>
		{% endfor %}
	</div>
	<div class="bottom" style="position: absolute; bottom: 50px;">
		<a class="btn btn-dark" href="{% url 'idolfulllist' %}">Click here for the full list</a>
		<a class="btn btn-dark" href="{% url 'idolregister' %}">Click here to register new Idol</a>
	</div>
{% endblock %}